apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rideshare
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rideshare.ijeaweledivine.online
      secretName: tls-rideshare
  rules:
    - host: rideshare.ijeaweledivine.online
      http:
        paths:
          - path: /api/v1/drivers(/|$).*
            pathType: ImplementationSpecific
            backend:
              service:
                name: driver-service
                port:
                  number: 80
          - path: /api/v1/riders(/|$).*
            pathType: ImplementationSpecific
            backend:
              service:
                name: rider-service
                port:
                  number: 80
          - path: /api/v1/matching(/|$).*
            pathType: ImplementationSpecific
            backend:
              service:
                name: matching-service
                port:
                  number: 80
          - path: /api/v1/email(/|$).*
            pathType: ImplementationSpecific
            backend:
              service:
                name: email-service
                port:
                  number: 80
          - path: /api/trips(/|$).*
            pathType: ImplementationSpecific
            backend:
              service:
                name: trip-service
                port:
                  number: 80
          - path: /ws(/|$).*
            pathType: ImplementationSpecific
            backend:
              service:
                name: trip-service
                port:
                  number: 3006
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rideshare-frontend
                port:
                  number: 80