apiVersion: v1
kind: Service
metadata:
  name: trip-service
spec:
  type: ClusterIP
  selector:
    app: trip-service
  ports:
    - name: http
      port: 80
      targetPort: 3005
      protocol: TCP # Flask API
    - name: websocket
      port: 3006
      targetPort: 3006 
      protocol: TCP # WebSocket Gateway
